/**
    @file   WbsCfgI2cBridge.h
    @author %TPL_USER%
    @date   %TPL_DATE%

    @COPYRIGHT (c) SOLECTRIX GmbH, Germany, %TPL_YEAR%, All rights reserved
     The copyright to the document(s) herein is the property of SOLECTRIX GmbH
     The document(s) may be used and/or copied only with the written permission
     from SOLECTRIX GmbH or in accordance with the terms/conditions stipulated
     in the agreement/contract under which the document(s) have been supplied
*/

#ifndef MODULES_WBSCFGI2CBRIDGE_H
#define MODULES_WBSCFGI2CBRIDGE_H

#include "drivers/sx/sfr.h"

#include "os/Types.h"

#include "utils/Compiler/Attributes.h"
#include "utils/lint/lint.h"

/**
 * Register offsets
 */
#define WBSCFGI2CBRIDGE_CONFIG_OFFSET            (0x00000000U)
#define WBSCFGI2CBRIDGE_STATUS_OFFSET            (0x00000004U)


/**
 * Signal structs and defines
 */
#define WBSCFGI2CBRIDGE_CONFIG_DEVADDR_LENGTH (7U)
#define WBSCFGI2CBRIDGE_CONFIG_CLKDIV_LENGTH (16U)
typedef struct COMPILER_ATTRIBUTE(packed) {
    __IO Bitfield_t DEVADDR : 7;
    __IO Bitfield_t : 9;
    __IO Bitfield_t CLKDIV : 16;
} WBSCFGI2CBRIDGE_CONFIG_bits;

__IO_REG32_BIT(WBSCFGI2CBRIDGE_CONFIG, WBSCFGI2CBRIDGE_CONFIG_bits);

#define WBSCFGI2CBRIDGE_CONFIG_REG(base) \
    LINT_SUPPRESS_CAST \
    (*(__IO WBSCFGI2CBRIDGE_CONFIG_type*)((uint32_t)base + WBSCFGI2CBRIDGE_CONFIG_OFFSET)) \
     LINT_RESTORE
#define WBSCFGI2CBRIDGE_CONFIG(base) \
    LINT_SUPPRESS_CAST \
    (*(__IO WBSCFGI2CBRIDGE_CONFIG_type*)((uint32_t)base + WBSCFGI2CBRIDGE_CONFIG_OFFSET)).RAW \
    LINT_RESTORE
#define WBSCFGI2CBRIDGE_CONFIG_bit(base) \
    LINT_SUPPRESS_CAST \
    (*(__IO WBSCFGI2CBRIDGE_CONFIG_type*)((uint32_t)base + WBSCFGI2CBRIDGE_CONFIG_OFFSET)).BITS \
    LINT_RESTORE

#define WBSCFGI2CBRIDGE_STATUS_LENGTH (32U)
#define WBSCFGI2CBRIDGE_STATUS_I2CCARRIERIDLE (1UL << 31UL)
#define WBSCFGI2CBRIDGE_STATUS_I2CCOREIDLE (1UL << 30UL)
#define WBSCFGI2CBRIDGE_STATUS_I2CCOREEN (1UL << 29UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXACCTYPE (1UL << 24UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRNACKREPDEVADR (1UL << 14UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRNACKDATLSB (1UL << 13UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRNACKDATMSB (1UL << 12UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRNACKADRLSB (1UL << 11UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRNACKADRMSB (1UL << 10UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRNACKDEVADR (1UL << 9UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRARBREPDEVADR (1UL << 8UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRARBRESTART (1UL << 7UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRARBDATLSB (1UL << 6UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRARBDATMSB (1UL << 5UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRARBADRLSB (1UL << 4UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRARBADRMSB (1UL << 3UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRARBDEVADR (1UL << 2UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRARBSTART (1UL << 1UL)
#define WBSCFGI2CBRIDGE_STATUS_TRXERRADR (1UL << 0UL)
typedef struct COMPILER_ATTRIBUTE(packed) {
    __IO Bitfield_t STATUS : 32;
} WBSCFGI2CBRIDGE_STATUS_bits;

__IO_REG32_BIT(WBSCFGI2CBRIDGE_STATUS, WBSCFGI2CBRIDGE_STATUS_bits);

#define WBSCFGI2CBRIDGE_STATUS_REG(base) \
    LINT_SUPPRESS_CAST \
    (*(__IO WBSCFGI2CBRIDGE_STATUS_type*)((uint32_t)base + WBSCFGI2CBRIDGE_STATUS_OFFSET)) \
     LINT_RESTORE
#define WBSCFGI2CBRIDGE_STATUS(base) \
    LINT_SUPPRESS_CAST \
    (*(__IO WBSCFGI2CBRIDGE_STATUS_type*)((uint32_t)base + WBSCFGI2CBRIDGE_STATUS_OFFSET)).RAW \
    LINT_RESTORE
#define WBSCFGI2CBRIDGE_STATUS_bit(base) \
    LINT_SUPPRESS_CAST \
    (*(__IO WBSCFGI2CBRIDGE_STATUS_type*)((uint32_t)base + WBSCFGI2CBRIDGE_STATUS_OFFSET)).BITS \
    LINT_RESTORE



/**
 * Register struct and defines
 */


#endif // MODULES_WBSCFGI2CBRIDGE_H
